name: Build
on:
  push:
    paths-ignore:
      - "**LICENSE"
      - "**.editorconfig"
      - "**.git**"
      - "!.github/workflows/**"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
        with:
          submodules: recursive

      - name: Cache
        uses: actions/cache@v4.2.3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget

      - name: Build client
        run: dotnet publish --configuration Debug --output build --verbosity normal

      - name: Upload client plugin
        uses: actions/upload-artifact@v4.6.2
        with:
          name: "io.github.nonperforming.pulse.dll"
          path: |
            build/io.github.nonperforming.pulse.dll
            build/io.github.nonperforming.pulse.pdb
          if-no-files-found: error
